# Generated by Django 4.2 on 2023-04-11 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='token',
            name='bank',
            field=models.CharField(choices=[('RASTRIYA BANIJYA BANK LIMITED', 'Rastriya Banijya Bank Limited'), ('NEPAL BANK LIMITED', 'Nepal Bank Limited'), ('SIDDHARTHA BANK LIMITED ', 'Siddhartha Bank Limited'), ('AGRICULTURE DEVELOPMENT BANK LIMITED', 'Agriculture Development Bank Limited')], default='RASTRIYA BANIJYA BANK LIMITED', max_length=150),
        ),
    ]
