# Generated by Django 4.2 on 2023-04-18 12:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0002_token_bank'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='token',
            name='bank',
        ),
    ]
