# Generated by Django 4.2 on 2023-04-18 13:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0003_remove_token_bank'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Token',
            new_name='Bank_Token',
        ),
    ]
