# Generated by Django 4.2 on 2023-04-18 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('office', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='citizen',
            name='phone_number',
            field=models.BigIntegerField(),
        ),
    ]
